[package]
name = "lilygo_t5"
version = "0.1.0"
authors = ["Juraj Michálek <juraj.michalek@espressif.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32-hal = "0.7.0"
esp-backtrace = { version = "0.4.0", features = ["esp32", "panic-handler", "print-uart"] }
xtensa-lx-rt = { version = "0.14.0", features = ["esp32"], optional = true }
esp-println = { version = "0.3.1", features = ["esp32"] }
embedded-hal-1     = { version = "=1.0.0-alpha.9", package = "embedded-hal" }
epd-waveshare = { path = "../epd-waveshare", version = "*" }
# epd-waveshare = { git = "https://github.com/georgik/epd-waveshare.git", branch = "experimental/lilogo-t5" }
embedded-graphics = "0.7.1"

[features]
default = ["rt", "esp32-hal/eh1"]
rt = ["xtensa-lx-rt"]
